Punto 1.

In [62]:
import numpy as np

class matriz:
  def __init__(self, msize:tuple, tipo:str, num:int):
    self._msize = msize
    self._tipo = tipo
    self._num = num
    self._matriz = []
  
  def crearMatriz(self):
    if self._tipo == "zeros":
      self._matriz = np.zeros(self._msize)
    elif self._tipo == "ones":
      self._matriz = np.ones(self._msize)
    elif self._tipo == "random":
      self._matriz = np.array(np.random.randint(20, 40, self._msize))
    print(self._matriz)
  
  #def multiplica(self):

In [64]:
tamano = (3,5); tipo = "random"
m = matriz(tamano, tipo, 3)
m.crearMatriz()

[[36 20 25 32 20]
 [24 20 36 39 31]
 [39 35 25 21 37]]


In [13]:
tamano = (3, 3)
tipo = "ones"

def mat(tam, tip):
  print(tam)
  print(tip)

mat(tamano, tipo)
type(tamano)
type(tipo)

(3, 3)
ones


str

Punto 2. 

In [54]:
class indentificacion:
  def __init__(self, nombre, edad):
    self.__nombre = nombre
    self.__edad = edad
  
  def sayHi(self):
    print(f"¡Hola, soy {self.__nombre} y tengo {self.__edad} años!")
  
johnny = indentificacion("Johnny Bravo", 39)
johnny.sayHi()

¡Hola, soy Johnny Bravo y tengo 39 años!
